### ISSUE TITLE
debug crash in win32 using openspotify-simple.exe (playlist.c)

### ISSUE THREAD

**Issue by nomis2k** [noahwilliamsson/openspotify#3]
Using windows 7, MS C++ express 2008, debug build

Built without problems.

Unhandled exception at 0x01361ead in openspotify-simple.exe: 0xC0000005: Access violation reading location 0xfeeeff02.

Seems to be lines 206 and 207 of playlist.c

DSFYDEBUG("Error on channel '%s', will retry request in %dms\n", ch->name, callback_ctx->req->next_timeout - get_millisecs());

**Comment by noahwilliamsson** [comment]
Thanks! Fixed with commit 917013f60772df9374c05bcfd3e32dcf2965523a
