### ISSUE TITLE
Please add a pkg-config file

### ISSUE THREAD

**Issue by Schnouki** [noahwilliamsson/openspotify#5]
The official libspotify provides libspotify.pc, a pkg-config file which can be used by cmake, autotools or plain Makefiles to detect which version of the lib is installed and what flags must be used by the compiler and the linker.

It would be very nice to have the same with openspotify.

I included one in the package I made for Arch Linux : http://aur.archlinux.org/packages/libopenspotify-git/libopenspotify-git/libopenspotify.pc.in. @@VER@@ is replaced by a version number when building the package (the version number is the date the git repo was cloned). Something similar in the official repo would be great.

**Comment by noahwilliamsson** [comment]
Fixed with commit http://github.com/noahwilliamsson/openspotify/commit/f5a34ab9cfc2547718221bdeb782ca817fa215a7
