### ISSUE TITLE
Cached search lookup fails for multiple searches with different parameters

### ISSUE THREAD

**Issue by jkp** [noahwilliamsson/openspotify#8]
I'm writing an object-oriented wrapper around libopenspotify using objective-c: in order to store references to my object wrappers I use the userdata pointer.  I'm having problems though because of the code you have implemented that returns cached versions of a given search based on the search term: it does not take into account the userparam parameter at all, which means I'm often getting references to dead objects returned to me.

In your code you have this comment:

/\* FIXME: Should hash on all input parameters! */

For now I'm going to comment out the caching in my copy: how would you see this caching / hashing working ideally?

**Comment by noahwilliamsson** [comment]
Good catch.
I realized there is no point in considering a search a reusable object in the same way tracks, albums and artists are.
This problem also existed with artistbrowses, albumbrowses and toplistbrowses.

I've now removed the "caching" code in all four of these cases.
Hopefully I didn't break anything in the process.

Please pull the latest sources and see if it works.
I've changed the layout of internal structures so be sure to do a 'make clean' before rebuilding the library.

Btw, have you seen http://github.com/rsms/spotifycocoa ?

**Comment by jkp** [comment]
Hey Noah

Yeah, I removed it my code and all has been well since then.

Thanks for the pointer to spotifycocoa...looks interesting.  I did a search but missed that somehow :)

**Comment by jkp** [comment]
This is fixed now I think...closing!

**Comment by noahwilliamsson** [comment]
Thanks for the feedback!
