### ISSUE TITLE
Is there a chance to support Radio ?

### ISSUE THREAD

**Issue by Kitof** [noahwilliamsson/openspotify#9]
This function is very useful in the official client.

Is there a possibility to add this feature to the library ?

The goal after that is to add radio support into xbmc ;)

**Comment by noahwilliamsson** [comment]
The radio part is apparently using some specialized search queries that are not exposed in libspotify at the moment.
If you want libspotify to support it the best way is to let Spotify know about it by requesting it here:
http://www.getsatisfaction.com/spotify/products/spotify_spotify_api_service

Libopenspotify will not support this feature until it's available in libspotify so I'm closing this comment.

**Comment by Kitof** [comment]
Sorry to "reopen", but the choice to not implement a function in libopenspotify who is not available in libspotify is a global policy or just a choice for radio support ?

If it's a policy, I've to understand than libopenspotify it's just an ideological library and not a way to have more functionnality than the proprietary library ?

**Comment by noahwilliamsson** [comment]
Ideally I would like libopenspotify to be a drop-in-replacement for libspotify and vice versa but I don't really have some kind of policy to refuse to support things libspotify doesn't.

I have no plans on investigating how the radio stuff in Spotify works but that could change if Spotify decides to add this feature to libspotify.

Either way, my point is that if you miss a feature that's not even implemented in libspotify you should put up a request for it in Spotify's API forum at GetSatisfaction.com. Requesting it there and eventually end up getting official support for it from Spotify would benefit everyone, not just those who track libopenspotify.

**Comment by Kitof** [comment]
Thanks for your quick and complete answer.

I submit my request to GetSatisfaction.com.

For the "policy" of libopenspotify, could you imagine 2 branches (or 2 fork) of libopenspotify ? One in drop-in-remplacement and another with more and/or experimental features ?
